### ISSUE TITLE
Does this work on windows?

### ISSUE THREAD

**Issue by bgSosh** [papandreou/node-optipng#5]
I'm having an issue where optimised pngs are being written without content (zero length) - however, it's not reporting any errors.

 If I remove node-optipng from the chain (e.g. just a source->dest copy) then the file is created ok.   

I'm testing this on window - is the OS supported?

**Comment by papandreou** [comment]
I honestly don't know if Windows is supported, but some fixes for both Windows and node.js 0.12 went into 0.2.1, which was released after you opened this issue. Could you try upgrading and see if that fixes it?

**Comment by bgSosh** [comment]
New version seems to work on windows.
